### We have created testUser(assume id = 5)
POST http://0.0.0.0:8080/users
Content-Type: application/json
Accept: application/json

{
  "userName": "testUser6",
  "firstName": "User 6",
  "lastName": "Ya posle decouplings heh",
  "birthDate": "",
  "gender": "",
  "email": "test@test.com",
  "password": "testpassword",
  "phone": "",
  "role": "student"
}

### Login as user. Dont forget to fetch the token
POST http://0.0.0.0:8080/users/login
Content-Type: application/json
Accept: application/json

{
  "userName": "testUser4",
  "password": "testpassword"
}



### Now let's get in as admin. You should always have admin created in your DB with role admin
POST http://0.0.0.0:8080/users/login
Content-Type: application/json
Accept: application/json

{
  "userName": "testUser",
  "password": "testpassword"
}

### Dont forget to fetch token

### Let's change the name of testUser5
PUT http://0.0.0.0:8080/users/testUser
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDczNzYzMTAsImlhdCI6MTYwNzM3MjcxMCwianRpIjoiNDQ1MDJiMmQ4OTAxYjg4ZGY5NzU5MmUyMmU2NDM2YWMifQ.l3kC_FPMu_3eRPE2ey_TsCUIQ7Xowod7bw8XZLXfY3A

{
  "userName" : "updatedUser",
  "firstName" : "",
  "lastName" :  "",
  "birthDate" : "",
  "gender" :  "",
  "email" : "newemail@test.com",
  "hash" :  "",
  "phone" : "",
  "role" :  "",
  "created" : "",
  "id" :  ""
}

### Let's see what have happened to testUser5

DELETE http://0.0.0.0:8080/users/testUser6
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MDczNzYzMTAsImlhdCI6MTYwNzM3MjcxMCwianRpIjoiNDQ1MDJiMmQ4OTAxYjg4ZGY5NzU5MmUyMmU2NDM2YWMifQ.l3kC_FPMu_3eRPE2ey_TsCUIQ7Xowod7bw8XZLXfY3A



###